### ISSUE TITLE
IFC Model tree is messy and misses a lot information

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepobouncer#499] opened 2021-09-02 13:33 UTC
### Description

Users are unable to identify element layers easily. In the end, they miss valuable information or are unable to navigate the model in the Tree card.

- This is happening in: prod
- This requires a hotfix to production: no

### Steps to replicate
- Upload the following IFC model to 3D Repo: [IFC Model](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Clients/Customers/Mid%20Group/Support/210902/IFC%20Models/P1031-BBA-ZZ-ZZ-MR-A-0001.ifc)
- Click on a wall
- Look at the model tree

### Current Behaviour
- Lots of **n/a** or **xxxxx** (can't tell what on earth is this?)

### Expected Behaviour
- Look nice and clear as with any other IFC model viewing platform (BIM Vision or Solibri)

### Pictures/ Gifs of the error
**Model Tree in 3D Repo**
![image](https://user-images.githubusercontent.com/19904513/131852316-e03a6a35-6b8b-4c82-8362-c0ecb020e281.png)

**Model Tree in Solibri**
![image](https://user-images.githubusercontent.com/19904513/131852650-7f8910b5-64bd-448c-9819-04dc9e108c81.png)

**Model in BIM Vision**
![image](https://user-images.githubusercontent.com/19904513/131852791-209314bc-810d-4a2c-974a-f6e5dcc8f398.png)

**Comment by carmenfan** [comment] 2021-09-02 13:43
@BDavydov we really didn't make these names up... This is the line item for the object within the IFC File: 
![image](https://user-images.githubusercontent.com/11945337/131854403-dbe90e9e-e95e-4c52-a51f-97ed55f54e79.png)

And here is a slab they decided to name `XXXXXX`:
![image](https://user-images.githubusercontent.com/11945337/131854509-7ed83e64-a8cb-48b7-8cff-22f351405b35.png)

**Comment by BDavydov** [comment] 2021-09-02 14:39
@carmenfan I see, you're absolutely right, there is no name given. I think it's the fact that we are unable to group our model tree differently ie. by Level then Category, making things difficult. @mosment3DRepo  If we could implement that in the future, it would make it a whole lot easier for our users and make our model interaction more robust.

**Comment by carmenfan** [comment] 2022-10-17 17:14
Closing this as it's working as intended

**Closed by carmenfan** 2022-10-17 17:14 UTC
